version: "2"
linters:
  enable:
    - forbidigo
    - gocognit
    - gocritic
    - gocyclo
    - misspell
    - nakedret
    - prealloc
    - staticcheck
    - unparam
  disable:
    - depguard
    - funlen
    - lll
    - mnd
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
